# Run with ansible-playbook -i inventories/lab 01_Initialize_Netbox.yml -e inv=lab
---
- hosts: netbox.local
  connection: local
  gather_facts: False
  collections:
    - netbox.netbox

  vars:
    template_root: "{{ template_dir | default('device_types/') }}"

  tasks:
    - name: Load netbox variables
      include_vars:
        file: inventories/{{ inv | default('lab') }}/host_vars/netbox.local.yml
        name: netbox
      tags: [ 'always' ]
      run_once: True

    - name: Initialize Netbox from fresh install
      vars:
        - netbox_state: present
      block:
        - name: Setup US Region
          netbox_region:
            netbox_url: "{{ netbox.url }}"
            netbox_token: "{{ netbox.token }}"
            data:
              name: United States
              slug: us
            state: "{{ netbox_state }}"

        - include: tasks/netbox/region.yml
          loop: "{{ regions }}"
          loop_control:
            loop_var: region
        - include: tasks/netbox/rirs.yml
          loop: "{{ rirs }}"
          loop_control:
            loop_var: rir
        - include: tasks/netbox/aggregate.yml
          loop: "{{ aggregates }}"
          loop_control:
            loop_var: aggregate
        - include: tasks/netbox/manufacturer.yml
          loop: "{{ manufacturers }}"
          loop_control:
            loop_var: manufacturer
        - include: tasks/netbox/platform.yml
          loop: "{{ platforms }}"
          loop_control:
            loop_var: platform
        - include: tasks/netbox/device_role.yml
          loop: "{{ device_roles }}"
          loop_control:
            loop_var: device_role
        - include: tasks/netbox/ipam_role.yml
          loop: "{{ ipam_roles }}"
          loop_control:
            loop_var: ipam_role
        - name: Create Initial Prefixes
          netbox_prefix:
            netbox_url: "{{ netbox.url }}"
            netbox_token: "{{ netbox.token }}"
            data:
              prefix: "{{ item.prefix }}"
              prefix_role: global-pool
            state: present
          loop: "{{ aggregates }}"

    - name: "Find files reccursively in root diretory {{ template_root }}"
      find:
        paths:
          - "{{ template_root }}"
        patterns:
          - ".*\\.yml"
          - ".*\\.yaml"
        file_type: file
        use_regex: True
        recurse: True
        depth: 2
      register: template_files

    - name: "Parse file data for filenames from directory"
      set_fact: template_files="{{ template_files.files | map(attribute='path') | list }}"

    - name: "Get templates vars from imported files"
      include_vars:
        file: "{{ item }}"
      with_items: "{{ template_files }}"
      register: templates

    - name: "Cleanup templates tree"
      set_fact:
        templates: "{{ templates.results | map(attribute='ansible_facts') | list }}"

    - name: "Build device template in Netbox"
      netbox_device_type:
        netbox_url: "{{ netbox.url }}"
        netbox_token: "{{ netbox.token }}"
        data:
          manufacturer: "{{ item['manufacturer'] }}"
          model: "{{ item['model'] }}"
          slug: "{{ item['slug'] }}"
          u_height: "{{ item['u_height'] if defined | default(false) else omit  }}"
          is_full_depth: "{{ item['is_full_depth'] if defined | default(false) else omit }}"
        state: present
      with_items: "{{ templates }}"
      loop_control:
        label: "{{ item['model'] }}"
