---

# Baseline Configurations
name_servers:
  - 8.8.8.8
  - 4.4.4.4
ntp_servers:
  - ntp0.cmllab.test
  - ntp1.cmllab.test
aaa_config:
  hostname: aaa.cmllab.test
  key: tacacs

syslog_server: log.cmllab.test

mdt:
  hostname: 172.16.30.10
  port: 5790

management_network:
  vrf_name: Mgmt-intf
  gateway: 172.16.100.1
  mask: 255.255.255.0

# Global Routing Config
bgp_asn: 65001

igp:
  type: isis
  core: SP_CORE
  access: SP_ACCESS

mpls:
  ldp_enable: True

segment_routing:
  enable: True
  prefer: False
  ti_lfa: False

multicast_routing:
  enable: False

core_prefixes:
  ipv4:
    - description: Core Range v4
      prefix_length: 22
      prefix_role: core-pri-pool
    - description: Core Loopbacks v4
      prefix_length: 26
      prefix_role: core-loopbacks
    - description: Core Interconnects v4
      prefix_length: 25
      prefix_role: core-interconnects
  ipv6:
    - description: Core Range v6
      prefix_length: 52
      prefix_role: core-pri-pool
    - description: Core Loopbacks v6
      prefix_length: 64
      prefix_role: core-loopbacks
    - description: Core Interconnects v6
      prefix_length: 64
      prefix_role: core-interconnects
