---
# CML unmanaged switch

hostname: unmanaged-switch-1
id: 100

interfaces:
  - type: port
    number: 0
    remote_node_id: 10
  - type: port
    number: 1
    remote_node_id: 11
  - type: port
    number: 2
    remote_node_id: 40
  - type: port
    number: 3
    remote_node_id: 41
  - type: port
    number: 4
    remote_node_id: 42
  - type: port
    number: 5
    remote_node_id: 43
  - type: port
    number: 6
    remote_node_id: 90
  - type: port
    number: 7
    remote_node_id: 91
  - type: port
    number: 31
    remote_node_id: 101
