---
- name: Setup {{ manufacturer.name }} Manufacturer
  netbox_manufacturer:
    netbox_url: "{{ netbox.url }}"
    netbox_token: "{{ netbox.token }}"
    data: "{{ manufacturer }}"
    state: present